#server
server:
  port: 8805

#---------产品图片--------------------------
qycpjs:
  savePath: /usr/java/8804/D://xfxh//upload//
  fileServerUrl: http://61.161.226.197:8090
  vueServerUrl: http://61.161.226.197:8090
#------------------------------------------------------------
#spring
spring:
  profiles:
    active: dev       ## produce
  druid:
    #配置druid连接池
    datasource:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  mybatis:
    mapperLocations: classpath:mapper/*-mapper.xml
    typeAliasesPackage: com.syfri.portalservice
    basePackage: com.syfri.portalservice.dao
    configuration:
      cacheEnabled: false
      lazyLoadingEnabled: false
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
#------------------------------------------------------------
#pagehelper分页插件设置
pagehelper:
  helper-dialect: oracle
  reasonable: true
  support-methods-arguments: true
  row-bounds-with-count: true
  auto-dialect: true
#------------------------------------------------------------
logging:
  level:
    root: info
    com.syfri.portalservice.dao: debugger
  level.com.syfri: debug
  path: logs/
  file: portalservice.log
  ##########################################################
  ###################  开发环境的profile  ###################
  ##########################################################
---
spring:
  profiles: dev
  druid:
    #配置druid连接池
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@10.119.119.205:1521/XFXHDB
#      url: jdbc:oracle:thin:@localhost:1521/orcl
      username: XFXHZH
      password: XFXHZH

  ##########################################################
  ###################  正式环境的profile  ###################
  ##########################################################
---
spring:
  profiles: produce
  druid:
    #配置druid连接池
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@10.119.123.25:1521/XFXHDB
      username: XFXHZH
      password: XFXHZH


  ##########################################################
  ###################  正式环境的profile  ###################
  ##########################################################
---
spring:
  profiles: localhost
  druid:
    #配置druid连接池
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521/XFXHDB
      username: XFXHZH
      password: XFXHZH
